### ISSUE TITLE
SSL handshake failure

### ISSUE THREAD

**Issue by frank-rahn** [wpmudev/broken-link-checker#10]
The following URLs provide all an SSL handshake failure.
- https://www.gi.de/ 
- https://openwrt.org/ 
- https://matt.aimonetti.net/posts/2013/06/26/practical-guide-to-graphite-monitoring/ 

`Log: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [Error #35]`
`=== (Keine Antwort) ===`
`    `
`    Response headers`
`    ================`

**Comment by dgw** [comment]
Using a recent version of openssl without SSLv3 enabled?

**Comment by da2x** [comment]
@frank-rahn, this is not an issue with broken-link-checker. SSLv3 has been deprecated and disabled in most server software and browsers for some time.
