### ISSUE TITLE
pt_BR translation

### ISSUE THREAD

**Issue by EPuncker** [wpmudev/broken-link-checker#16]
I've updated the Brazilian portuguese translations, I do not know if this is the right place to post since I'm kinda new here, I don't know how to attach a file either so I've uploaded a zip file containing the files into depositfiles

http://depositfiles.com/files/gxmnxby58

**Comment by mrxkon** [comment]
Hey @EPuncker , late reply here but for future reference all translations can be done directly to wp.org so your locale GTE and PTEs can check if everything is ok as well :) Ref: https://translate.wordpress.org/locale/pt-br/default/wp-plugins/broken-link-checker/
