### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by da2x** [wpmudev/broken-link-checker#26]
The project doesn’t have a license. Please include a LICENSE file in the root of the repository, and add this add the License property to the top of the readme.txt file as required by the WordPress plugin hosting directory.

Note that this project distributes components under a lot of different licenses. I can’t advise on what licenses would be compatible with all of these, however – from my limited understanding, GPLv2 should work assuming all code contributors consent to having their contributions licensed with this license.

For simplicity, assume all contributions from myself are public domain. I agree to whatever license the project maintainer chooses without restrictions or compensation.

**Comment by alexstandiford** [comment]
Hey @da2x - Just a heads up this is in the WordPress repository and as such is is required to run on a GPL license.

**Comment by mrxkon** [comment]
Thanks for the report @da2x :) Even though as @alexstandiford mentions all plugins have to follow GPL to be on the wp.org repos it's never bad to add the information within the plugins as well for redistribution purposes.
