### ISSUE TITLE
Multisite-usage of your plugin

### ISSUE THREAD

**Issue by Trike27** [wpmudev/broken-link-checker#4]
Hello,

I want to use your plugin on my multisite-installation, but I get the following error message:

"Broken Link Checker installation failed. Try deactivating and then reactivating the plugin.
Please activate the plugin separately on each site. Network activation is not supported.

Failed to load plugin settings from the "wsblc_options" option.

Option doesn't exist in the wp_4_options table."

It would be great if you could integrate multisite-usage in your plugin in future releases.

Thanks in advance,
Martin

**Comment by mrxkon** [comment]
Hey @Trike27 , late reply here. I'll close this but I've passed this internally now on our WPMU DEV plans as we took over maintenance to see what we can do regarding multisites :)

**Comment by mundschenk-at** [comment]
Still happening for me on one site. Previously there was no problem with multisite (and the plugin has been network activated for ages - which may be the problem here, the site in question is pretty new).
