### ISSUE TITLE
Request to transfer Broken Link Checker plugin

### ISSUE THREAD

**Issue by HongPong** [wpmudev/broken-link-checker#52]
Hello,

I would request to transfer ownership of the plugin "Broken Link Checker" which has not been updated in several years, is no longer compatible with current PHP versions, and I understand has been sold to your organization.

My handle on WordPress.org is "HongPong" ( https://profiles.wordpress.org/hongpong/ ) and I have been a free software community participant and contributor since 2005 on WordPress and for 12 years in the Drupal community. I have experience with similar link scanning software having worked on "linkback" and "vinculum" modules in Drupal 7 and 8 which perform remote checks on inbound and outbound links including Webmentions. I also have extensive experience with managing community open source software packages including issue queues, code quality, linting, security, maintainability and so on.

If there are any concerns about this, please let me know. I believe this is appropriate since this is a widely used plugin by the community and it should be maintained in the interest of the overall health of the Internet's killer feature: working links.

Best regards,
Dan Feidt (hongpong@hongpong.com)

**Comment by mrxkon** [comment]
Hey @HongPong , the repo has been transferred over to WPMU DEV as we will be maintaining the plugin from now on.

I'll close this issue :) .
