### ISSUE TITLE
create_function fix erroneously reverted

### ISSUE THREAD

**Issue by archon810** [wpmudev/broken-link-checker#57]
https://github.com/ManageWP/broken-link-checker/pull/34/commits/0dd1ebfbb9236aaa2d78a47b14f81a196f56acf9 got reverted by https://github.com/ManageWP/broken-link-checker/commit/4b504e899938098217b2082d5091d30673e3c0e6.

Why? Please fix.

**Comment by archon810** [comment]
In fact, https://github.com/ManageWP/broken-link-checker/blob/master/core/core.php#L957 is also still using `create_function` for some reason.

**Comment by Zrgisa** [comment]
Hi, it was not reverted by mistake. create_function currently only gives a warning in PHP 7 as far as I know, while anonymous functions do not work in PHP 5.2. The change would break PHP 5.2 compatibility and with that some of the websites currently using this plugin.

**Comment by archon810** [comment]
PHP 5.2 was released in 2016. It's time to drop support for it - people running 5.2 can continue using the current version, but don't penalize people running updated software please.

**Comment by Zrgisa** [comment]
ideally it would be turned into a named function and just put as a callback that way. That would work in both the older and newer PHP versions. If you have a sec to do it, feel free to make the change, I'll gladly accept it.

A warning is one thing, completely crashing older versions is another :)

**Comment by mundschenk-at** [comment]
WordPress 5.2 requires PHP 5.6, so anything below is dead.

**Comment by Beee4life** [comment]
Sad to see this is still an issue, 1 month after the OP posted it while it's such an easy fix.

**Comment by HermanMonteiro** [comment]
Can anyone tell me if this plugin is compatible with Wordpress version 5.2.2?

**Comment by SukcesStrony** [comment]
Yeah, having support for PHP 5.2 nowadays is like a joke... I mean I know that the WordPress core might still have it but this isn't a crucial plugin and can move forward for the benefit of people who actually do update their software once every 10 years or so.

**Comment by Beee4life** [comment]
> having support for PHP 5.2 nowadays is like a joke...

for sure....

**Comment by archon810** [comment]
@mrxkon Any idea when the 1.11.10 version with the fix is going to be released in the WP repo?

Thanks.
