### ISSUE TITLE
Version compatible Wordpress?

### ISSUE THREAD

**Issue by HermanMonteiro** [wpmudev/broken-link-checker#60]
Can anyone tell me if this plugin is compatible with Wordpress version 5.2.2?

**Comment by HongPong** [comment]
You can use my fork which should be working as expected on 5.2.2 
* https://github.com/hongpong/broken-link-checker

**Comment by mrxkon** [comment]
We're checking everything against 5.3 at the moment and if something isn't yet fully compatible ( I don't see anything at the moment ) it will be brought up to latest WP version as well :) .

You can also always check the latest tested version on wp.org repository and on readme.txt here on the first lines as `Tested up to: WP_VERSION`
