### ISSUE TITLE
rename readme.txt to readme.markdown

### ISSUE THREAD

**Issue by spiralofhope** [wpmudev/broken-link-checker#73]
GitHub supports Markdown, and it appears that `readme.txt` is already written that syntax.

**Comment by dgw** [comment]
`readme.txt` is [part of the WordPress plugin standard](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/). Renaming it would break that.

**Comment by spiralofhope** [comment]
I understand.

Duplicating it into another filename is probably annoying.

With some quick searches, I see no way to configure the `.txt` to be processed as Markdown.

[Symbolic links](https://github.com/git-for-windows/git/wiki/Symbolic-Links) is technically possible but unrealistic and stupid.
